C-Sharp/ASPNET_Core/BeltPrep/TheWall/Controllers/LARController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using TheWall.Models;

namespace WeddingPlanner.Controllers;

public class LARController : Controller
{
    private readonly ILogger<LARController> _logger;

    private MyContext db;

    public LARController(ILogger<LARController> logger, MyContext context)
    {
        _logger = logger;

        db = context;
    }

    // LOGIN AND REGISTRATION PAGE
    [HttpGet("")]
    public IActionResult Index()
    {
        return View();
    }
    
    // CREATE NEW USER 
    [HttpPost("/users/create")]
    public IActionResult CreateUser(User newUser)
    {
        if(!ModelState.IsValid)
        {
            return View("Index");
        }
        PasswordHasher<User> Hasher = new PasswordHasher<User>();
        newUser.Password = Hasher.HashPassword(newUser, newUser.Password);

        db.Add(newUser);
        db.SaveChanges();

        HttpContext.Session.SetInt32("loggedUserId", newUser.UserId);

        return RedirectToAction("Index", "Wall");
    }

    // LOGIN AN EXISTING USER
    [HttpPost("/users/login")]
    public IActionResult Login(LoginUser loginUser)
    {   
        if(!ModelState.IsValid)
        {
            return View("Index");
        }

        User? existingUser = db.Users.FirstOrDefault(x => x.Email == loginUser.LoginEmail);

        if (existingUser == null)
        {
            ModelState.AddModelError("LoginEmail", "Invalid credentials");
            return View("Index");
        }

        PasswordHasher<LoginUser> hasher = new PasswordHasher<LoginUser>();
        var result = hasher.VerifyHashedPassword(loginUser, existingUser.Password, loginUser.LoginPassword);

        if (result == 0){
            ModelState.AddModelError("LoginEmail", "Invalid credentials");
            return View("Index");
        }
        HttpContext.Session.SetInt32("loggedUserId", existingUser.UserId);

        return RedirectToAction("Index", "Wall");
    }

    // LOGOUT
    [HttpPost("users/logout")]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

C-Sharp/ASPNET_Core/BeltPrep/TheWall/Views/LAR/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="mt-20 mx-20 flex justify-around">
    <div>
        <h1 class="text-6xl font-semibold text-blue-500">Register</h1>
        @await Html.PartialAsync("_Register")
    </div>

    <div>
        <h1 class="text-6xl font-semibold text-green-500">Login</h1>
        @await Html.PartialAsync("_Login")
    </div>
</div>

C-Sharp/ASPNET_Core/BeltPrep/TheWall/Views/LAR/_Login.cshtml
@model LoginUser

<form asp-action="Login" asp-controller="LAR" method="post" class="mt-10 flex flex-col gap-2">
    <span asp-validation-for="LoginEmail" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="LoginEmail" class="text-2xl">Email: </label>
        <input asp-for="LoginEmail" class="input-priv">
    </div>

    <div class="flex gap-10 items-center justify-between">
        <label asp-for="LoginPassword" class="text-2xl">Password: </label>
        <input asp-for="LoginPassword" class="input-priv">
    </div>

    <div class="flex justify-center items-center mt-10">
        <button class="submit-btn">Login</button>
    </div>
</form>

C-Sharp/ASPNET_Core/BeltPrep/TheWall/Views/LAR/_Register.cshtml
@model User

<form asp-action="CreateUser" asp-controller="LAR" method="post" class="mt-10 flex flex-col gap-2 justify-center">
    <span asp-validation-for="FirstName" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="FirstName" class="label-priv">First Name: </label>
        <input asp-for="FirstName" class="input-priv">
    </div>

    <span asp-validation-for="LastName" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="LastName" class="label-priv">Last Name: </label>
        <input asp-for="LastName" class="input-priv">
    </div>

    <span asp-validation-for="Email" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="Email" class="label-priv">Email: </label>
        <input asp-for="Email" class="input-priv">
    </div>

    <span asp-validation-for="Password" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="Password" class="label-priv">Password: </label>
        <input asp-for="Password" class="input-priv">
    </div>

    <span asp-validation-for="ConfirmPassword" class="error-message"></span>
    <div class="flex gap-10 items-center justify-between">
        <label asp-for="ConfirmPassword" class="label-priv">PW Confirm: </label>
        <input asp-for="ConfirmPassword" class="input-priv">
    </div>

    <div class="flex justify-center items-center mt-10">
        <button class="submit-btn">Register</button>
    </div>
</form>