C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Models/ChefModel.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ChefsNDishes.Models;

public class Chef
{
    [Key]
    public int ChefId {get;set;}

    [Required(ErrorMessage = "First Name is required")]
    [Display(Name = "First Name:")]
    public string FirstName {get;set;}

    [Required(ErrorMessage = "Last Name is required")]
    [Display(Name = "Last Name:")]
    public string LastName {get;set;}

    [Required]
    [DataType(DataType.Date)]
    [BirthdayValidator]
    [Display(Name = "Date of Birth:")]
    public DateTime Birthday {get;set;}

    public List<Dish> AllDishes {get;set;} = new List<Dish>();
}

public class BirthdayValidatorAttribute : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        
        if((DateTime)value > DateTime.Now)
        {
            return new ValidationResult("This is in the future! Please enter a date from the past...");  
        } 
        else
        {
            TimeSpan diff = DateTime.Now.Date - (DateTime)value;
            int years = diff.Days/365;
            if(years < 18)
            {
                return new ValidationResult($"According to our calculations, you are {years} years old and too young to register");
            }
            else
            {
                return ValidationResult.Success;
            }
        }
    }
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Models/Context.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace ChefsNDishes.Models;

public class MyContext : DbContext 
{   
    public MyContext(DbContextOptions options) : base(options) { }    
    public DbSet<Dish> Dishes { get; set; } 
    public DbSet<Chef> Chefs {get;set;}
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Models/DishContext.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace ChefsNDishes.Models;


public class DishContext : DbContext 
{   
    public DishContext(DbContextOptions options) : base(options) { }    
    public DbSet<Dish> Dishes { get; set; } 
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Models/DishModel.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ChefsNDishes.Models;

public class Dish
{
    [Key]
    public int DishId {get;set;}

    [Required]
    public string Name {get;set;}

    [Required]
    [Range(0, double.PositiveInfinity, ErrorMessage = "Calories must be greater than 0")]
    public int Calories {get;set;}

    [Required]
    public int Tastiness {get;set;}

    [Required]
    public int ChefId {get;set;}

    public Chef? Creator {get;set;}
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Models/ErrorViewModel.cs
namespace ChefsNDishes.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Controllers/ChefController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using ChefsNDishes.Models;

namespace ChefsNDishes.Controllers;

public class ChefController : Controller
{
    private readonly ILogger<ChefController> _logger;

    private MyContext db;

    public ChefController(ILogger<ChefController> logger, MyContext context)
    {
        _logger = logger;

        db = context;
    }

    [HttpGet("")]
    public IActionResult Index()
    {   
        List<Chef> ViewModel = db.Chefs.Include(x => x.AllDishes).ToList();


        return View(ViewModel);
    }

    [HttpGet("chefs/add")]
    public IActionResult AddChef()
    {
        return View();
    }

    [HttpPost("chefs/create")]
    public IActionResult ProcessChef(Chef newChef)
    {
        if(!ModelState.IsValid)
        {
            return View("AddChef");
        }

        db.Chefs.Add(newChef);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using ChefsNDishes.Models;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;

    private MyContext db;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;

        db = context;
    }

    [HttpGet("dishes")]
    public IActionResult Dishes()
    {   
        List<Dish> ViewModel = db.Dishes.Include(x => x.Creator).ToList();
        return View(ViewModel);
    }

    [HttpGet("dishes/add")]
    public IActionResult AddDish()
    {   
        ViewBag.allChefs = db.Chefs.ToList();
        return View();
    }

    [HttpPost("dishes/create")]
    public IActionResult ProcessDish(Dish newDish)
    {
        if (!ModelState.IsValid)
        {
            return View("AddDish");
        }

        db.Dishes.Add(newDish);
        db.SaveChanges();
        return RedirectToAction("Dishes");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Views/Chef/AddChef.cshtml
@{
    ViewData["Title"] = "Add Chef";
}

@model Chef

<div class="title-header">
    <h1 class="title-header-text">Add a Chef</h1>
</div>
<div class="flex justify-center mt-20 mx-96">
    <form asp-action="ProcessChef" asp-controller="Chef" method="POST" class="flex flex-1 flex-col justify-evenly gap-2">
        <span asp-validation-for="FirstName" class="error-message"></span>
        <div class="flex justify-between items-center">
            <label asp-for="FirstName" class="label-priv"></label>
            <input asp-for="FirstName" class="input-priv">
        </div>

        <span asp-validation-for="LastName" class="error-message"></span>
        <div class="flex justify-between items-center">
            <label asp-for="LastName" class="label-priv"></label>
            <input asp-for="LastName" class="input-priv">
        </div>

        <span asp-validation-for="Birthday" class="error-message"></span>
        <div class="flex justify-between items-center">
            <label asp-for="Birthday" class="label-priv"></label>
            <input asp-for="Birthday" class="input-priv">
        </div>

        <div>
            <button class="submit-btn">Submit</button>
        </div>
    </form>
</div>

C-Sharp/ASPNET_Core/ORM/ChefsNDishes/Views/Chef/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Chef>

<div class="title-header">
    <h1 class="title-header-text">Check out our roster of chefs!</h1>
</div>

<table class="table table-fixed mt-10">
    <thead>
        <tr>
            <td>Name</td>
            <td>Age</td>
            <td># of Dishes</td>
        </tr>
    </thead>
    <tbody>
        @foreach (Chef chef in Model)
        {
            <tr>
                <td>@chef.FirstName @chef.LastName</td>
                <td>@(DateTime.Now.Year - chef.Birthday.Year)</td>
                <td>@chef.AllDishes.Count</td>
            </tr>
        }
    </tbody>
</table>