C-Sharp/ASPNET_Core/BeltPrep/WeddingPlanner/Controllers/WeddingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers;

[SessionCheck]
public class WeddingController : Controller
{
    private readonly ILogger<WeddingController> _logger;

    private MyContext db;

    public WeddingController(ILogger<WeddingController> logger, MyContext context)
    {
        _logger = logger;

        db = context;
    }

    // INDEX PAGE
    [HttpGet("weddings")]
    public IActionResult Index()
    {   
        List<Wedding> allWeddings = db.Weddings
                                        .Include(x => x.Associations)
                                        .ToList();

        ViewBag.loggedUser = db.Users.FirstOrDefault(x => x.UserId == HttpContext.Session.GetInt32("loggedUserId"));
        return View(allWeddings);
    }

    // PLAN A WEDDING PAGE
    [HttpGet("weddings/add")]
    public IActionResult Plan()
    {
        ViewBag.loggedUser = db.Users.FirstOrDefault(x => x.UserId == HttpContext.Session.GetInt32("loggedUserId"));
        return View();
    }

    // CREATE A WEDDING PAGE
    [HttpPost("weddings/create")]
    public IActionResult CreateWedding(Wedding newWedding)
    {
        if(!ModelState.IsValid)
        {   
            ViewBag.loggedUser = db.Users.FirstOrDefault(x => x.UserId == HttpContext.Session.GetInt32("loggedUserId"));
            return View("Plan");
        }
        db.Weddings.Add(newWedding);
        db.SaveChanges();
        return RedirectToAction("ShowOne", new {WeddingId = newWedding.WeddingId});
    }

    // SHOW ONE WEDDING
    [HttpGet("/weddings/{WeddingId}")]
    public IActionResult ShowOne(int WeddingId)
    {
        Wedding? wedding = db.Weddings
                            .Include(x => x.Associations)
                            .ThenInclude(x => x.User)
                            .FirstOrDefault(x => x.WeddingId == WeddingId);
        ViewBag.loggedUser = db.Users.FirstOrDefault(x => x.UserId == HttpContext.Session.GetInt32("loggedUserId"));
        return View(wedding);
    }

    // DELETE A WEDDING
    [HttpPost("weddings/{WeddingId}/delete")]
    public IActionResult DeleteOne(int WeddingId)
    {
        Wedding? weddingToDelete = db.Weddings.FirstOrDefault(x => x.WeddingId == WeddingId);
        int? LoggedUser = (int)HttpContext.Session.GetInt32("loggedUserId");
        if(weddingToDelete.UserId == LoggedUser)
        {
            db.Weddings.Remove(weddingToDelete);
            db.SaveChanges();
            return RedirectToAction("Index");
        } 
        else 
        {
            return RedirectToAction("Index");
        }
    }

    // TOGGLE RSVP
    [HttpPost("weddings/{WeddingId}/RSVP")]
    public IActionResult ToggleRSVP(int WeddingId, int UserId)
    {
        Association? existingRSVP = db.Associations
                                        .FirstOrDefault(x => x.UserId == UserId && x.WeddingId == WeddingId);
        if(existingRSVP != null)
        {
            db.Associations.Remove(existingRSVP);
        }
        else
        {
            Association newAssociation = new Association()
            {
                WeddingId = WeddingId,
                UserId = UserId
            };
            db.Associations.Add(newAssociation);
        }
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

public class SessionCheckAttribute : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        int? userId = context.HttpContext.Session.GetInt32("loggedUserId");
        if(userId == null)
        {
            // Redirect to the Index page if there was nothing in session
            // "Home" here is referring to "HomeController", you can use any controller that is appropriate here
            context.Result = new RedirectToActionResult("Index", "LAR", null);
        }
    }
}

C-Sharp/ASPNET_Core/BeltPrep/WeddingPlanner/Views/Wedding/Index.cshtml
@{
    ViewData["Title"] = "Wedding Dashboard";
}

@model List<Wedding>

<nav class="flex justify-between p-10 text-align items-center">
    <h2 class="text-2xl font-semibold">Welcome @ViewBag.loggedUser.FirstName</h2>
    <div class="flex text-xl gap-5">
        <a href="/weddings">Home</a>
        <a href="/weddings/add">Plan a Wedding</a>
        <form asp-action="Logout" asp-controller="LAR" method="POST">
            <button>Logout</button>
        </form>
    </div>
</nav>
<table class="table text-2xl">
    <thead>
        <tr>
            <th>Wedding Of</th>
            <th>Date</th>
            <th>Guest Count</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Wedding wedding in @Model)
        {
            <tr>
                <td><a href="/weddings/@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a></td>
                <td>@wedding.WeddingDate.ToString("MMM dd, yyyy")</td>
                <td>@wedding.Associations.Count</td>
                <td>
                    @{if (wedding.Creator?.UserId == ViewBag.loggedUser.UserId)
                    {   
                        @* Delete Functionality *@
                        <form asp-action="DeleteOne" 
                            asp-controller="Wedding" 
                            asp-route-WeddingId="@wedding.WeddingId" 
                            method="POST">
                            <button>Delete</button>
                        </form>
                    }
                    else if (wedding.Associations.Any(x => x.WeddingId == wedding.WeddingId && x.UserId == ViewBag.loggedUser.UserId))
                    {
                        @* Un-RSVP Functionality *@
                        <form asp-action="ToggleRSVP" 
                            asp-controller="Wedding" 
                            asp-route-WeddingId="@wedding.WeddingId" 
                            method="POST">
                            <input type="hidden" name="UserId" value="@ViewBag.loggedUser.UserId">
                            <button>Un-RSVP</button>
                        </form>
                    }
                    else 
                    {
                        @* RSVP Functionality *@
                        <form asp-action="ToggleRSVP" 
                            asp-controller="Wedding" 
                            asp-route-WeddingId="@wedding.WeddingId" 
                            method="POST">
                            <input type="hidden" name="UserId" value="@ViewBag.loggedUser.UserId">
                            <button>RSVP</button>
                        </form>
                    }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

C-Sharp/ASPNET_Core/BeltPrep/WeddingPlanner/Views/Wedding/Plan.cshtml
@{
    ViewData["Title"] = "Plan";
}

@model Wedding

<nav class="flex justify-between p-10 text-align items-center">
    <h2 class="text-2xl font-semibold">Welcome @ViewBag.loggedUser.FirstName</h2>
    <div class="flex text-xl gap-5">
        <a href="/weddings">Home</a>
        <a href="/weddings/add">Plan a Wedding</a>
        <a href="/users/logout">Logout</a>
    </div>
</nav>
<h1 class="text-5xl font-bold">Plan a Wedding</h1>
<form asp-action="CreateWedding"
    asp-controller="Wedding"
    method="POST"
    class="flex flex-col gap-2 p-8 w-1/3"
    >
    <span asp-validation-for="WedderOne" class="error-message"></span>
    <div class="flex justify-between items-center gap-5">
        <label asp-for="WedderOne" class="label-form"></label>
        <input asp-for="WedderOne" class="input-priv">
    </div>

    <span asp-validation-for="WedderTwo" class="error-message"></span>
    <div class="flex justify-between items-center gap-5">
        <label asp-for="WedderTwo" class="label-form"></label>
        <input asp-for="WedderTwo" class="input-priv">
    </div>

    <span asp-validation-for="WeddingDate" class="error-message"></span>
    <div class="flex justify-between items-center gap-5">
        <label asp-for="WeddingDate" class="label-form">Date: </label>
        <input asp-for="WeddingDate" class="input-priv">
    </div>

    <span asp-validation-for="WeddingAddress" class="error-message"></span>
    <div class="flex justify-between items-center gap-5">
        <label asp-for="WeddingAddress" class="label-form">Address: </label>
        <input asp-for="WeddingAddress" class="input-priv">
    </div>

    <input type="hidden" name="UserId" value="@ViewBag.loggedUser.UserId">

    <div>
        <button class="submit-btn">Create</button>
    </div>
</form>

C-Sharp/ASPNET_Core/BeltPrep/WeddingPlanner/Views/Wedding/ShowOne.cshtml
@{
    ViewData["Title"] = "Show";
}

@model Wedding

<nav class="flex justify-between p-10 text-align items-center">
    <h2 class="text-2xl font-semibold">Welcome @ViewBag.loggedUser.FirstName</h2>
    <div class="flex text-xl gap-5">
        <a href="/weddings">Home</a>
        <a href="/weddings/add">Plan a Wedding</a>
        <a href="/users/logout">Logout</a>
    </div>
</nav>

<h1 class="text-5xl font-bold">@Model.WedderOne & @Model.WedderTwo's wedding</h1>

<h2 class="text-3xl font-semibold mt-8">Date: @Model.WeddingDate.ToString("MMM dd, yyyy")</h2>

<div class="flex flex-col">
    <h3 class="text-2xl font-semibold mt-8">Guests: </h3>
    <div class="guest-list-container">
        @foreach (Association association in @Model.Associations)
        {
            <p>@association.User.FirstName @association.User.LastName</p>
        }
    </div>
</div>